### PR TITLE
Introduce deduction for wrong answers

### PR DESCRIPTION
**Pull request by PhilippImhof**
As discussed in #19, I have prepared a PR that allows for a deduction in case of wrong answers. Please see the details below:

### For adminsitrators

New setting for administrators

### For teachers

As long as the administrator does not allow the deduction, the interface for teachers does not change:
No change if not allowed

If deductions are allowed, a new field is added. The default value is 0, so that no deduction is made unless the teacher explicitly sets one
New option if allowed

### Grading

With a deduction of 0.5, we first get 0.5 (out of 1) mark for 1 (out of 2) correct answers. However, for the one wrong answer, we get `0.5*0.5 = 0.25` deduction. The final grade is thus 0.25.

Grading with deduction

Questions might have a deduction defined, e.g. if imported from another site (even one's own) where such deductions are allowed. However, if the admin has blocked deductions, they will not be considered. Thus, it is not possible for a teacher to circumvent the institution's policy on that matter:

Grading without deduction

### Testing

The PR contains acceptance tests for the following:
* check that deductions are not allowed by default
* check that the deduction field is shown if and only if deductions are allowed
* check that deductions are validated as a floating point number >=0 and <=1
* check that exported questions before and after this change can be imported (with the `<deduction>` attribute present or not)
* check that deductions are considered for the grading if and only if they are allowed

The PR contains one additional unit test:
* check that the deduction is correctly calculated

### CODE REVIEW

**Comment by PhilippImhof** [comment]
Regarding #22, I suggest doing the following:

Clear button

Pressing the icon (might be another one and it will have a proper label for accessibility) will reset the radio buttons of the corresponding row.

IMHO, the icon *must* be present whenever the penalty deduction is allowed and set. (Students must have a possibility to get back to a neutral answer when they risk losing points for wrong answers.) Independently, there could be an admin setting that allows the icon for any question. In that case, it should be configurable per question. However, there's not really a need (nor a benefit) for this with questions where wrong answers do not count.

Should I proceed with that idea?

**Comment by PhilippImhof** [comment]
Regarding #22, I have now added the following: If the question has a deduction (and deductions are enabled), there is a trash can icon in every row that allows clearing the checked radio button in that row:

with reset

If, however, deductions are disabled or the question does not have one, the icon will not be shown:

without reset

IMHO, the icon *must* be present whenever the penalty deduction is allowed and set. (Students must have a possibility to get back to a neutral answer when they risk losing points for wrong answers.) 

Independently, there could be an admin setting that allows the icon for any question. In that case, it should be configurable per question. However, IMHO, there's not really a need (nor a benefit) for this with questions where wrong answers do not count. But I will gladly add that option, if you think I should.

**Comment by PhilippImhof** [comment]
@tkorner, would you mind having a look at this?

**Comment by tkorner** [comment]
Hi you have made some bigger and additional changes. We will take a closer look an discuss it within 2 weeks. best regards. T.

**Comment by nexterday** [comment]
Hi Philip, apologies for the delay. I have discussed the changes with Thomas et al, and we reached into an agreement that it makes better sense if we add the deduction as a grading method (radio button under MTF 0/1 radio) and on selection of this deduction radio, the field of deduction value, to appear. In this way we guarantee no confusion about MTF 0/1 grading (either all or nothing grade). For other aspects, we are happy to accept them, but please mind mobile.php to allow option clearance when deduction is enabled at admin side AND is selected as grading method in the question edit form. 

once you are done with the changes, please let us know so we can thorough test the changes and then we can merge the code onto our repo.

Thanks again for the great work!

**Comment by PhilippImhof** [comment]
Thanks for the feedback and especially the hint regarding the mobile version which I completely forget. I will gladly change the code according to your suggestions and let you know once I am ready.

**Comment by nexterday** [comment]
Once ready, please create a new pull request. Thanks!

**Comment by PhilippImhof** [comment]
@nexterday I am just finishing the tests and came across a strange thing: When using `moodlehq/moodleapp:3.9.4` docker version to test mobile features with Ionic 3, it says the question type mtf is not supported. I tried with Moodle 4.0 and Moodle 3.11. I have the problem also with current master and with commit 7d1fad0d, e.g. the one before you updated to Ionic 5.

It all works fine with the current app and Ionic 5. Can you confirm you have it working with Ionic 3? What version of the app do you use for your tests? And what version of Moodle?

**Comment by nexterday** [comment]
Hi Phillip, 
See here: https://github.com/ethz-let/moodle-qtype_mtf/blob/ac328387e0549b6b388c3f76f83b03a9dde6d712/classes/output/mobile.php#L45

Our support for ionic3 is temporary and we kept it there for some institutes who still use ionic3 - you should not worry about the older inoic3 html file anymore. It will be removed going forward.

**Comment by PhilippImhof** [comment]
@nexterday Thanks, I saw that, that's why I chose 3.9.4 for the Ionic 3 test. But I get that there is no need to make changes to the Ionic3 template. (Which IMHO is a good choice, because the switch from Ionic 3 to 5 happened in August 2021.)

I will probably clean up and finish everything in the next few days and then submit the new PR.

**Pull request closed without merging**
