### PR TITLE
Introduce deduction for wrong answers

### PR DESCRIPTION
**Pull request by PhilippImhof**
Most of this change is already explained in #23. Just some remarks about differences to what I wrote there:

* Mobile support for Ionic 5 (Moodle App >= 3.9.5) is now included. Thanks for reminding me of that...
* As requested, I created a scoring method "Subpoints with deductions". The method won't be shown in the edit form, unless the administrator allows deductions to be made.
* If the new scoring method is chosen, the edit form will show a field to enter the deduction. The default value is now set to 0.5 in these cases, as it seems clear that the user actually wants a deduction. However, the deduction will still be set to 0.0 if other scoring methods are chosen. (The value has no importance at all for questions using the classic "Subpoints" or "1/0" scoring methods.)
* As before, any deductions stored in the DB (e.g. via imported questions or because deductions used to be allowed) will be discarded, if the admin decides to block that option. 
* If the user edits a question using the "Subpoints with deduction" method on a site where this option is not allowed, they will not be able to save it without choosing a valid option. The setting is not changed automatically, because the user should be made aware of the change:
Deductions no longer allowed
* As space is limited on mobile devices, I do not use the trash can there, but allow the user to "unset" the radio button; a thing that is not possible (well, it could be done, but it is highly uncommon) on normal computers:

https://user-images.githubusercontent.com/52650214/213917655-1e764780-5068-4eac-a5af-3b737fe40cc5.mov

* If the administrator sets "Subpoints with deduction" as the default method, the option "Allow penalty deductions" will automatically be activated upon saving. If they deactivate that option while still having "Subpoints with deduction" as default, it will be turned back up.

I am looking forward to your feedback @tkorner & @nexterday

### CODE REVIEW

**Comment by nexterday** [comment]
Hi Philip, thanks for the update. We will check the code and do thorough test and if all in order, we will merge the code and update you. Thank you again and please note that the person involved in QA is very occupied at the moment, so it might take slightly longer time until we close it.

**Comment by nexterday** [comment]
Hi Philip @PhilippImhof 

MTF deduction: German description on admin page missing. see screenshot.

When you fix it, please make sure the commit has “fixed EMDL-620“ wording in order for us to track changes internally.

**Comment by PhilippImhof** [comment]
Thanks for the feedback @nexterday. Somehow, the screenshot is missing. Can you tell me which text it is?

**Comment by nexterday** [comment]
Apologies, attached again.

**Comment by nexterday** [comment]
Commit: EMDL-622

issue: MTF deduction: Changing scoring method to subpoints will not remove trash bins.

How to reproduce:
create a quiz with a MTF question, using scoring method "Subpoints with deduction"
preview the question: trash bins are displayed for each option to remove the choice
alter the scoring method to "Subpoints"
preview the question again
Observed:
trash bins are still displayed


Expected:
no trash bins are displayed since they only apply to scoring method "Subpoints with deduction"
Remark:
When creating a MTF question with scoring method "Subpoints" in the first place, trash bins are not displayed:

BC0ACF83-B4FE-4B35-9F2E-84541343F467
4625C5EA-E1A5-496C-9715-9D2C5ED2DE45

**Comment by nexterday** [comment]
Commit EMDL-623: MTF deduction: preview demands all options answered before check is possible.

to reproduce:
create a quiz with one MTF question, scoring type "Subpoints with deduction"
configure 4 options, one true and three false
preview the question from the question settings page
Check three of the options, leave one unanswered
press the "check" button
Observation:
An error message appears: "Please answer all parts of the question."

Expected:
It is not neccessary to check all options, the evaluation should take place at any rate (like it when actually taking the quiz).
Remark:
Same behavior with scoring method "Subpoints"
 
 
1E5B2587-7C2E-4E54-851C-A8F7CD1B8422

**Comment by nexterday** [comment]
Commit EMDL-621: Quiz navigation inconsitent across scoring methods 


How to reproduce:
create a quiz with three MTF questions and assign the following scoring methods:
q1: subpoints with deduction
q2: subpoints
q3: MTF 1/0
solve the quiz as student, and answer each question only partwise
switch several times between questions without changing answer options (just to be sure navigation is updated).
click on "finish attempt"
Observation:
q1 and q3 are indicated as "Not yet answered" while q2 is marked as "Incomplete answer" (as well as in column Status as in the Quiz navigation)
Expected:
All questions should be indicated the same (probably as "Incomplete answer")

When this quiz is submitted, the confirmation dialog states that all three questions are without answer:
9F9001A3-EF72-4404-A185-2944DAAEA3FA
DFB6D70C-C149-4304-9632-F108399BADB8
725B829F-A9BF-48CE-AEF0-59CAE6BEC6F4

This, however, is also reflected in the quiz navigation of the review mode after submit (but still seems wrong)

**Comment by nexterday** [comment]
Issue EMDL-624: unanswered option leads to score of zero (bug or feature?)

How to reproduce:

create a quiz with one MTF question containing 4 options (one true, the other three false)
configure scoring method "Subpoints with deduction" and "Deduction if wrong" = 0.5
solve the quiz as student and leave one answer unchecked
submit the quiz

Observed:

In the deferred feedback and on the result page of the quiz, the score of the question is zero
Expected:

Leaving one option out should still yield a result, like with scoring method "Subpoints", shouldn't it?

Just a thought: If all options have to be checked anyway, the trash bin would not make much sense? So I concluded, that this case (i.e. leaving one option out) has not been properly considered / implemented. But I have no idea from the description in [Introduce deduction for wrong answers by PhilippImhof · Pull Request #23 · ethz-let/moodle-qtype_mtf (github.com)](https://github.com/ethz-let/moodle-qtype_mtf/pull/23), what the desired behavior in this case would be. Should only the options actually checked be considered, as with "Subpoints"?

**Comment by PhilippImhof** [comment]
Thanks for your checks and your feedback @nexterday. I have some questions left:

### EMDL-621

This issue is related to EMDL-623. The difference in behaviour is due to this:

https://github.com/ethz-let/moodle-qtype_mtf/blob/ac328387e0549b6b388c3f76f83b03a9dde6d712/question.php#L225-L235

I think it absolutely makes sense for "subpoints with deduction" and "subpoints" to have the same behaviour, I simply forgot to make that change when I moved the deduction into its own scoring method. However, I'd rather not change anything for the 1/0 method, as that would be beyond the scope of this PR. 

**Question**: Would you want me to change it in order for all methods to behave in the same way?

### EMDL-622

I have currently no idea how this is possible, as the text is clearly there:

https://github.com/ethz-let/moodle-qtype_mtf/blob/c66b67d6118557d5f284cc18918b8b3089964f79/lang/de/qtype_mtf.php#L84

It even contains a copy-paste error that I will fix as soon as I have found the problem.

### EMDL-623

As mentioned above, this is related to EMDL-621. The same happens not only for "subpoints", as you already mentioned, but also for "1/0". AFAIK, this is Moodle's default behaviour. The code above says that the question is not "gradable". I could change that, but I am not sure you want me to do so. Even less, if you would want me to do so for all scoring methods.

**Question** Please clarify what you would want me to do.

### EMDL-624

Thanks for pointing this out. The error comes from the fact that 

https://github.com/ethz-let/moodle-qtype_mtf/blob/c66b67d6118557d5f284cc18918b8b3089964f79/grading/qtype_mtf_grading_subpointdeduction.class.php#L47-L57

Only counts the rows that were graded "correct", so it does not distinguish between wrong and empty rows. I will correct that.

**Comment by nexterday** [comment]
- EMDL-620 (language missing. note: its not EMDL-622): yes its good, leave it as-is (with the new text correction).
- EMDL-621: yes please add the condition for deduction, and leave MTF 0/1 alone. Note: the deduction will only work when answers are given (part or full answers) <-- we keep it as-is until/unless someone comes asking for different behaviour.
- EMDL-622 (trash bin issue): see details https://github.com/ethz-let/moodle-qtype_mtf/pull/24#issuecomment-1400524481 
- EMDL-623: please leave it as is. we will take standard moodle behaviour. 
- EMDL-624: thanks!

**Comment by spillinge** [comment]
Just one more observation from the tests concerning the trash bin issue (EMDL-622): As it seems, trash bins are always displayed, if a value was set in "Deduction if wrong", irrespective of the actual scoring method ...

**Comment by PhilippImhof** [comment]
AFAICS I have them all now. I am still trying to hunt down the problem that causes `get_string` to fetch the wrong (old) text for `scoringmethod_help`.

**Comment by nexterday** [comment]
Thanks Philip, re text: increase the version and remove cache. 

Ps would be cool if you can add behat tests doe grading with deduction (see our feature files as an example)

**Comment by PhilippImhof** [comment]
Caches are purged, version was changed, but did not make a difference. If I set the key to `scoringmethodx_help`, it works. If I change it back, it does not. If I use the German text in the English file, it works. Setting `debugstringids` shows that the right string is taken from the right package. I have raised the problem in the Moodle dev chat.

There is a behat test:

https://github.com/ethz-let/moodle-qtype_mtf/blob/076a6028b0114992082ba44cef461f1b2f6ccfbc/tests/behat/deduction.feature#L117-L151

I'll gladly add more. What kind of additional behat test would you like to have? I thought about adding one to make sure the trash bins disappear when switching back to another method than "subpoints with deductions", as a consequence of EMDL-622.

Also, after EMDL-624 I added something to the walkthrough test, to make sure that empty rows will never be counted as wrong again.

**Comment by nexterday** [comment]
I think because its suffixed with _help which is used for help icon in edit form and being indexed already. We might need a totally new identifier (say scroingmethodinfo or so) in order to keep specific for config description.

re behat - that is cool, thanks a mil

**Comment by PhilippImhof** [comment]
> I think because its suffixed with _help which is used for help icon in edit form and being indexed already. We might need a totally new identifier (say scroingmethodinfo or so) in order to keep specific for config description.

I thought about that. But that would mean that the string is duplicated, because the same text is shown in the question edit form. (However, it would make it possible to have different texts so that "subpoints with deductions" would not even show up in the help text if it is not allowed.)

Also, I discarded the possibility that it could be due to the `_help` suffix, because it works in English.

> re behat - that is cool, thanks a mil - a focus on regrading feature is much appreciated.

A check for the trash icon is on the way. (Made me find another glitch.) You mean regrading after changing the method from "subpoints" to "subpoints with deductions" and/or vice-versa?

**Comment by spillinge** [comment]
Concerning behat feature for regrading: We also test for regrading after true/false flag was changes for some options, because this happens quite often with our examinators...

**Comment by PhilippImhof** [comment]
> Concerning behat feature for regrading: We also test for regrading after true/false flag was changed for some options, because this happens occasionally with our examinators...

I can do so, although that should probably be a unit test rather than an acceptance test, because it is internal rather than GUI related. I'll have a look at that.

**Comment by PhilippImhof** [comment]
Unit test for regrading is done: regrading after change of scoring method (with deductions to classic subpoints) and after change of correct answers while using deductions.

**Comment by spillinge** [comment]
Testing regrading: I also checked (manually) if a change in "Deduction if wrong" works with regrading (it does :-)). So if it is not in the unit test yet, you might wan to add a check for it? BTW, great work!

**Comment by PhilippImhof** [comment]
Thanks very much for the feedback and the suggestion. I added that to the unit test as well.

**Comment by nexterday** [comment]
Ah yes, german, italian and french are actually added by language contribution (https://lang.moodle.org/).

**Comment by PhilippImhof** [comment]
Found it all by now: Once the release is uploaded to the Moodle plugin database, its strings are fetched and incorporated into the language pack. Then, there's a scheduled task `\tool_langimport\task\update_langpacks_task` that runs at 04.55  everyday and updates the language pack. So people will have the correct strings at latest one day after the update.

I am still struggling to find out why the language files shipped with the plugin do not take precedence over the general language pack.

**Comment by nexterday** [comment]
I think the reason was that plugin developers usually do not add more than 1 language, hence contributors keep adding local language edits to the community because they cant contact every and each plugin dev to include or change languages. We are special case; we offered english and german

**Comment by nexterday** [comment]
@spillinge could you please update us once the test is done so we can merge shall everything is in order?

Thanks Phillip for the great work and brilliant communication.

**Comment by PhilippImhof** [comment]
It was a pleasure to work with you. Thanks for your tests and support.

**Comment by spillinge** [comment]
All issues solved and successfully re-tested - except the german description of new scoring method in admin settings, this will be handled by us. Therefore, from my side it is "go" for merging!

**Comment by PhilippImhof** [comment]
Thanks! Just an update re: language. According to the Moodle dev's, plugin authors should not ship their own translations. All (English) strings are fetched into [AMOS](https://lang.moodle.org/) and then translated. Translations shipped with the plugin will be superseded by strings from the language pack. So the strings we have here will only be taken into account if they do not have a translation in the language pack.

I have an account at AMOS anyway, so I will be able to submit our translations shortly after the release.

**Pull request merged**
